# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccfmt" do
  name "ccfmt"
  desc "CLI tool that formats ~/.claude.json"
  homepage "https://github.com/708u/ccfmt"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccfmt"

  on_macos do
    on_intel do
      url "https://github.com/708u/ccfmt/releases/download/v#{version}/ccfmt_Darwin_x86_64.tar.gz"
      sha256 "cbc72d78307532f2398079d5a069a1158a4ed695f7aed9f4c7bdd58aff40b033"
    end
    on_arm do
      url "https://github.com/708u/ccfmt/releases/download/v#{version}/ccfmt_Darwin_arm64.tar.gz"
      sha256 "d455b08eddebb9f69772ff956282334cc0980e69b4a9f26cbd377238cd11c8b3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/708u/ccfmt/releases/download/v#{version}/ccfmt_Linux_x86_64.tar.gz"
      sha256 "edcaf3b4c60bf398d4aba794526866df7a8f2b19fa375a38f64b5959cc566d28"
    end
    on_arm do
      url "https://github.com/708u/ccfmt/releases/download/v#{version}/ccfmt_Linux_arm64.tar.gz"
      sha256 "bdf55a74433607c1ae0b7160f218181f184cca04844e5fb5640e6dcce0eee2df"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccfmt"]
    end
  end

  # No zap stanza required
end
