# This file was generated by GoReleaser. DO NOT EDIT.
cask "cctidy" do
  name "cctidy"
  desc "CLI tool that formats ~/.claude.json"
  homepage "https://github.com/708u/cctidy"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cctidy"

  on_macos do
    on_intel do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Darwin_x86_64.tar.gz"
      sha256 "9aebcdc760de43ddd8eb78b2b4ace2f057a6d3db4cd87d2c66b288e07d1bcd99"
    end
    on_arm do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Darwin_arm64.tar.gz"
      sha256 "7b563e76a63628c13a3866cf23abc67dc4c8d0d5ebcd03557794df319eb7f388"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Linux_x86_64.tar.gz"
      sha256 "99fcf4a0b1976a77704dc4ef441536028a0f4f9fcbf3b730126265efeb243b78"
    end
    on_arm do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Linux_arm64.tar.gz"
      sha256 "06ccd6e42f555c0cb67085ce98a4c72e5c65a110b8b1a07d904f383b43410282"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cctidy"]
    end
  end

  # No zap stanza required
end
