# This file was generated by GoReleaser. DO NOT EDIT.
cask "cctidy" do
  name "cctidy"
  desc "CLI tool that formats ~/.claude.json"
  homepage "https://github.com/708u/cctidy"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cctidy"

  on_macos do
    on_intel do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Darwin_x86_64.tar.gz"
      sha256 "6f6462255ec059b2cbc1303d9b0d38dc8291f9623a8d71c42e9632663d86dd2a"
    end
    on_arm do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Darwin_arm64.tar.gz"
      sha256 "08cec860736d0679260620f45ec7afb3a99f80fb438c797b17cc49ca9cd7949c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Linux_x86_64.tar.gz"
      sha256 "2bbec0466c5dd908246abf5eb6235e85df98a83f9ea10e8c6b46fc86eeb56adb"
    end
    on_arm do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Linux_arm64.tar.gz"
      sha256 "66e91087e8f385ba5f84392e0374b106d1b68d2b638cbb00e7ba4e3dc8ecd102"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cctidy"]
    end
  end

  # No zap stanza required
end
