# This file was generated by GoReleaser. DO NOT EDIT.
cask "cctidy" do
  name "cctidy"
  desc "CLI tool that formats ~/.claude.json"
  homepage "https://github.com/708u/cctidy"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cctidy"

  on_macos do
    on_intel do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Darwin_x86_64.tar.gz"
      sha256 "1bc21aaedc6521db9c800b5f6535c02098f747cc0c3a38662cfa08efe2717c5d"
    end
    on_arm do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Darwin_arm64.tar.gz"
      sha256 "4f9e8a8baa5f85db53924cc2ca865b28edbb2d66d91aab2723d0d885a3144046"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Linux_x86_64.tar.gz"
      sha256 "7a3ab7a3f44ddd420450693493034de082534b36c4153325a3a943a7eeca8401"
    end
    on_arm do
      url "https://github.com/708u/cctidy/releases/download/v#{version}/cctidy_Linux_arm64.tar.gz"
      sha256 "b67395e59026bc83aff1c4a33b390de8013155ab2bc34560f562c664ccc6efad"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cctidy"]
    end
  end

  # No zap stanza required
end
