# This file was generated by GoReleaser. DO NOT EDIT.
cask "twig" do
  name "twig"
  desc "Simplify git worktree workflows with automatic branch creation, symlinks, and change syncing"
  homepage "https://github.com/708u/twig"
  version "0.10.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twig"
  bash_completion "completion/twig.bash"
  zsh_completion "completion/twig.zsh"
  fish_completion "completion/twig.fish"

  on_macos do
    on_intel do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Darwin_x86_64.tar.gz"
      sha256 "16a1c3e74ecd8b4a790131c7b03b665f9a93ebcaa2225d211df9b393c9ba4c1a"
    end
    on_arm do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Darwin_arm64.tar.gz"
      sha256 "a599309e37b43b044fc608fdc0c2ae4b05e66ccf80c13b9c2afe6667130e9e9f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Linux_x86_64.tar.gz"
      sha256 "5b5807fdf896cbc72c3f77ae4a6d343d2773d2671d2bc7d7d49c337ef3337dd7"
    end
    on_arm do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Linux_arm64.tar.gz"
      sha256 "f24c4f03fcc6a38a67f018ecb9ebdac9832eca78b8e009584b7bc5d8097f98b2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twig"]
    end
  end

  # No zap stanza required
end
