# This file was generated by GoReleaser. DO NOT EDIT.
cask "twig" do
  name "twig"
  desc "Simplify git worktree workflows with automatic branch creation, symlinks, and change syncing"
  homepage "https://github.com/708u/twig"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twig"
  bash_completion "completion/twig.bash"
  zsh_completion "completion/twig.zsh"
  fish_completion "completion/twig.fish"

  on_macos do
    on_intel do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Darwin_x86_64.tar.gz"
      sha256 "38c2dfbc3d244ef565ddc4ecb111f8f00a5e4178349edffd9302b8ac7fa9e7f2"
    end
    on_arm do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Darwin_arm64.tar.gz"
      sha256 "7602cec98323a20f9ab6c31f52b399650a8eb32a281be4540917ec4412304c2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Linux_x86_64.tar.gz"
      sha256 "b2ecf6a13b33229c388bff34186f27291f94e9afd832db801f067eda7d744fb6"
    end
    on_arm do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Linux_arm64.tar.gz"
      sha256 "5a516bbdb67f40c4178313a95dd4f19c15bdd99eed1b47c10b88fff1f6d60004"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twig"]
    end
  end

  # No zap stanza required
end
