# This file was generated by GoReleaser. DO NOT EDIT.
cask "twig" do
  name "twig"
  desc "Simplify git worktree workflows with automatic branch creation, symlinks, and change syncing"
  homepage "https://github.com/708u/twig"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twig"
  bash_completion "completion/twig.bash"
  zsh_completion "completion/twig.zsh"
  fish_completion "completion/twig.fish"

  on_macos do
    on_intel do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Darwin_x86_64.tar.gz"
      sha256 "ca85646e072afd5d777ca0cf79e8acdd0ad1915799649e56f008d83560587940"
    end
    on_arm do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Darwin_arm64.tar.gz"
      sha256 "ee2f9fdafe75080c338db7d789f3505f3fead6bb7d84e12146fb85f47e0bf056"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Linux_x86_64.tar.gz"
      sha256 "ae9fd64c945fd652334c28b583dcb7604df082f13974aad86bb5183aab83c57c"
    end
    on_arm do
      url "https://github.com/708u/twig/releases/download/v#{version}/twig_Linux_arm64.tar.gz"
      sha256 "6c100c3343c466ea6529d1d9be21fd456de07a9463fabc6deb29215ac128ad08"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twig"]
    end
  end

  # No zap stanza required
end
